### ISSUE TITLE
ResolvePackageNotFound

### ISSUE THREAD

**Issue by mms100** [sevahn/deconvolution#1]
Thanks for the great tool

I am struggling with creating the env to start the analysis.

I think the yml file is not compatible with my system macOS Bigsur.

I have also tried to move the packages needed from the dependencies to be under the pip but the error still persists.

Looking forward to having your appreciated feedback.

Many thanks in advance,

The Error:

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - libprotobuf==3.11.3=h8b12597_0
  - pango==1.40.14=he7ab937_1005
  - xorg-libxau==1.0.9=h14c3975_0
  - cryptography==2.8=py37h72c5cf5_1
  - libgcc-ng==9.2.0=h24d8f2e_2
  - libgfortran-ng==7.3.0=hdf63c60_5
  - sqlite==3.31.1=h7b6447c_0
  - ncurses==6.1=hf484d3e_1002
  - pygraphviz==1.5=py37h516909a_1001
  - graphite2==1.3.13=hf484d3e_1000
  - numpy==1.18.1=py37h95a1406_0
  - perl==5.26.2=h516909a_1006
  - libedit==3.1.20181209=hc058e9b_0
  - pyrsistent==0.15.7=py37h516909a_0
  - libffi==3.2.1=he1b5a44_1006
  - libtiff==4.1.0=hc3755c2_3
  - icu==64.2=he1b5a44_1
  - libtool==2.4.6=h14c3975_1002
  - gettext==0.19.8.1=hc5be6a0_1002
  - libiconv==1.15=h516909a_1005
  - libuuid==2.32.1=h14c3975_1000
  - xorg-libsm==1.2.3=h84519dc_1000
  - jpeg==9c=h14c3975_1001
  - pkg-config==0.29.2=h516909a_1006
  - harfbuzz==2.4.0=h9f30f68_3
  - pixman==0.38.0=h516909a_1003
  - lz4-c==1.8.3=he1b5a44_1001
  - cffi==1.13.2=py37h8022711_0
  - xorg-libx11==1.6.9=h516909a_0
  - freetype==2.10.0=he983fc9_1
  - xorg-kbproto==1.0.7=h14c3975_1002
  - glib==2.58.3=py37h6f030ca_1002
  - xorg-xproto==7.0.31=h14c3975_1007
  - jbig==2.1=h14c3975_2001
  - python==3.7.4=h265db76_1
  - cairo==1.16.0=hfb77d84_1002
  - libpng==1.6.37=hed695b0_0
  - xorg-libxpm==3.5.13=h516909a_0
  - xorg-libice==1.0.10=h516909a_0
  - xorg-xextproto==7.3.0=h14c3975_1002
  - conda-package-handling==1.6.0=py37h516909a_1
  - protobuf==3.11.3=py37he1b5a44_0
  - yaml==0.2.2=h516909a_1
  - pthread-stubs==0.4=h14c3975_1001
  - libxcb==1.13=h14c3975_1002
  - openssl==1.1.1g=h7b6447c_0
  - fontconfig==2.13.1=h86ecdb6_1001
  - xorg-libxdmcp==1.1.3=h516909a_0
  - yarl==1.3.0=py37h516909a_1000
  - openjpeg==2.3.1=h981e76c_3
  - pyyaml==5.3=py37h516909a_0
  - libgcc==7.2.0=h69d50b8_2
  - libxml2==2.9.10=hee79883_0
  - pandas==1.0.1=py37hb3f55d8_0
  - psutil==5.6.7=py37h516909a_0
  - libstdcxx-ng==9.2.0=hdf63c60_2
  - xorg-libxt==1.1.5=h516909a_1003
  - markupsafe==1.1.1=py37h516909a_0
  - expat==2.2.9=he1b5a44_2
  - libopenblas==0.3.7=h5ec1e0e_6
  - pycosat==0.6.3=py37h516909a_1002
  - xz==5.2.4=h14c3975_1001
  - fftw==3.3.8=nompi_h7f3a6c3_1110
  - datrie==0.8=py37h516909a_0
  - zlib==1.2.11=h516909a_1006
  - graphviz==2.38.0=hf68f40c_1011
  - xorg-libxext==1.3.4=h516909a_0
  - ruamel_yaml==0.15.80=py37h516909a_1000
  - wrapt==1.11.2=py37h516909a_0
  - pcre==8.43=he1b5a44_0
  - pynacl==1.3.0=py37h516909a_1001
  - xorg-libxrender==0.9.10=h516909a_1002
  - readline==7.0=hf8c457e_1001
  - libgomp==9.2.0=h24d8f2e_2
  - tk==8.6.10=hed695b0_0
  - zstd==1.4.4=h3b9ef0a_1
  - giflib==5.1.9=h516909a_0
  - multidict==4.7.4=py37h516909a_0
  - xorg-renderproto==0.11.1=h14c3975_1002

**Comment by sevahn** [comment]
The environment was exported on linux; the build specifications were exported with the dependencies.  These can be removed from the yml file; however, there are different package dependencies between macOS and linux so you will still likely find conflict in package versions.

It is advisable to run this code on a machine allows job parallelization as some samples can take awhile to deconvolve. On a Mac, here are the packages you need (supplying the same version from the yml file):
(1) python 3.7.4
(2) scikit-learn 0.24.2
(3) numpy 1.18.1
(4) cvx-opt 1.2.5 
(5) scipy 1.5.2
(6) scanpy 1.8.1  (note it is not needed for the deconvolve.py script, so you can remove the import line if you do not want to add to your environment)
