### ISSUE TITLE
adata.layers["decontXcounts"] of tabula sapiens scRNAseq data

### ISSUE THREAD

**Issue by byeongchangsim** [sevahn/deconvolution#2]
Hello, thank you so much for creating a good analytical tool.

In the code you uploaded, there is adata.X = adata.layers["decontXcounts"] of Fig1 deno.py . When I checked your method, it says that you downloaded the data of tabula_sapiens yourself. But I think you made the data of decontXcount yourself. Could you please download the data of tabula-sapiens and introduce how you made adata.layers["decontXcounts"]?

Thank you
@sevahn

**Comment by sevahn** [comment]
`decontXcounts` is a layer of the public version of the Tabula Sapiens object used in this work. You can check out the original publication (PMID: 35549404) for details about how this was created in the object.

**Comment by byeongchangsim** [comment]
> `decontXcounts` is a layer of the public version of the Tabula Sapiens object used in this work. You can check out the original publication (PMID: 35549404) for details about how this was created in the object.

Thank you for your response.

When I called tabula sapiens.h5ad to anndata, I asked because there was no layer. Can I get a paper-like source that finds a way to call layers together?

Thak you

**Comment by byeongchangsim** [comment]
I was stupid. When I downloaded and loaded from figshare, that layer existed.

I'm sorry to bother you.
