### ISSUE TITLE
Toden et al. cfRNA-seq metadata

### ISSUE THREAD

**Issue by byeongchangsim** [sevahn/deconvolution#3]
We would like to download and re-analyze PRJNA574438 among the data on the cell type of origin of cell-free transcripts published by your company. However, upon checking the data posted on SRA, we noticed discrepancies compared to the information presented in the paper. PRJNA574438 lacks the distinction between AD and NCI, and information about the university where the data was generated is also absent. Could you kindly provide clarification on how this data was divided into AD and Ctrl samples?

Thank you very much for publishing high-quality analytical tools and

**Comment by miti08** [comment]
Hello, it's been months but in case you (or any future readers) still have this issue, I have personally contacted the authors of Toden et al. and they have provided me with the missing metadata file (attached below). 

[ADsampleInfo.xlsx](https://github.com/sevahn/deconvolution/files/14491343/ADsampleInfo.xlsx)

**Comment by byeongchangsim** [comment]
@miti08 
Thank you for your response.

As for the attached file, I personally contacted Toden and others and received the same file.

An issue that did not match the data posted to NCBI occurred. The reason is that if you look at the attached file, the file 3272 is duplicated. In addition to this, several files are duplicated. If duplicate is not handled, NCI and AD cannot be distinguished.

And I attached two txt files.

In this txt file, when STAR alignment was performed with 1P and 2P generated after trimmomatic analysis in all samples, mapping reads were classified into 80% or more and less. When performing the analysis, was the proportion of mapping reads analyzed to be this low?

Thank you again for your response.
I look forward to hearing from you.


[filtered_output_above_80.txt](https://github.com/sevahn/deconvolution/files/14491399/filtered_output_above_80.txt)
[filtered_output_below_80.txt](https://github.com/sevahn/deconvolution/files/14491400/filtered_output_below_80.txt)

![Screenshot from 2024-03-05 15-37-35](https://github.com/sevahn/deconvolution/assets/79529451/c52a4831-a521-43cc-a49f-bf64809c0728)

**Comment by miti08** [comment]
@byeongchangsim 
I checked the authors' supplementary file and they stated that 96 samples have duplicate libraries. I think you can just pick one replicate between them like the authros did.  
![image](https://github.com/sevahn/deconvolution/assets/88759103/efdf1f1d-ffac-4cdf-bb73-40e9885c0bdc)

As for the other results, I have not performed alignment on the data yet, but I will do it soon and let you know of my results.

**Comment by byeongchangsim** [comment]
@miti08 
Thank you so much for your response.

As you said, we chose one of the replication samples but what I understood about that criteria was that we "created a technical replication from 96 samples that were treated first. But we don't know this order.

And you mentioned about data alignment.
You said you would proceed with the work and give me the result. Thank you so much for this.

The pipeline of the cfRNA-seq analysis I'm referring to is Professor miramou's github. Is this the way you're proceeding? If you have another pipeline, can I ask you to share it?

Thank you.
